on: [push]

jobs:
  deployment_job:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
    name: Deployment Job
    steps:
    - uses: actions/checkout@v3

    - name: SSH
      id:  ssh_to_server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
         touch /home/ubuntu/test
         ls
         
    - uses: act10ns/slack@v1
      with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#general'
      if: failure()
